C_OBJS=booter.o
ASM_OBJS=cos_asm_scheduler.o
COMPONENT=crboot.o
INTERFACES=cgraph pgfault checkpoint sched_hier
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
